version: '3.9'

networks:
  finik-dev:
    driver: bridge

services:
  finik.newsservice.web:
    image: ${DOCKER_REGISTRY-}finiknewsserviceweb
    build:
      context: .
      dockerfile: NewsService/Finik.NewsService.Web/Dockerfile
    networks:
      - finik-dev
    depends_on: 
      - postgres_db

  finik.authservice.web:
    image: ${DOCKER_REGISTRY-}finikauthserviceweb
    build:
      context: .
      dockerfile: AuthService/Finik.AuthService.Web/Dockerfile
    networks:
      - finik-dev
    depends_on: 
      - postgres_db

  finik.stocksandcompanies.webapi:
    image: ${DOCKER_REGISTRY-}finikstocksandcompanieswebapi
    build:
      context: .
      dockerfile: StocksAndCompanies/Finik.StocksAndCompanies.WebApi/Dockerfile
    networks:
      - finik-dev
    depends_on: 
      - postgres_db

  rabbitmq:
    container_name: finik-rabbitmq
    image: rabbitmq:3-management
    networks:
      - finik-dev
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: finik-redis
    image: redis:latest
    networks:
      - finik-dev
    restart: always
    ports:
      - "6379:6379"

  postgres_db:
    container_name: finik-postgres
    image: postgres:latest
    networks:
      - finik-dev
    environment:
      POSTGRES_PASSWORD: otus5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
